### ISSUE TITLE
Questions on the threshold determination for region mask

### ISSUE THREAD

**Issue by zynxxnn** [yu-lab-vt/AQuA#10]
Hi,

Thank you for sharing this useful toolbox :)
In the "Mask builder" function, when pressing "self" button to generate a region mask, how is the threshold automatically determined? Since the "intensity threshold" can only be ajusted by a scroll bar, I cannot set exactly the same threshold value for videos recorded from different exprimental days. It's also impossible to use only one region mask for all the videos as their FOVs could be slightly different (very similar though). But if I do not use any region mask, the extraction time would be too long. So I just want to make sure if using the automatically determined threshold is appropriate for unified analysis on data captured from long-term imaging. Thanks!

**Comment by XuelongMi** [comment]
Hi,

The threshold is determined by applying Otsu's method to the average projection of the data. In MATLAB, we use the function "**graythresh**", you can check it here: https://www.mathworks.com/help/images/ref/graythresh.html. This method chooses a threshold that minimizes the intraclass variance of the thresholded black and white pixels.

**Comment by zynxxnn** [comment]
> Hi,
> 
> The threshold is determined by applying Otsu's method to the average projection of the data. In MATLAB, we use the function "**graythresh**", you can check it here: https://www.mathworks.com/help/images/ref/graythresh.html. This method chooses a threshold that minimizes the intraclass variance of the thresholded black and white pixels.

Thank you very much for your answer!
