### ISSUE TITLE
Regarding the max and avg propagation speed

### ISSUE THREAD

**Issue by Srimayee-123** [yu-lab-vt/AQuA#11]
Everytime i use AQUA, the speed feature is always 'NaN.' Can you please update me as to what goes wrong?

**Comment by yu-lab-vt** [comment]
Hi, Srimayee-123, can you send in an example data set for us to diagnose? Please directly send email to mixl18@vt.edu and cc to yug@vt.edu

**Comment by Srimayee-123** [comment]
Hi,
Do you mean an already run cell along with its excel sheet after running
AQuA on it?
Thank you
Srimayee.

**Comment by yu-lab-vt** [comment]
I meant the raw input data and your parameter settings. You can have more direct communication with Xuelong Mi (mixl18@vt.edu).

**Comment by Srimayee-123** [comment]
Sure I’ll do that.
Thank you
Srimayee.
