### ISSUE TITLE
Is it one-photon imaging friendly?

### ISSUE THREAD

**Issue by DenovoW** [yu-lab-vt/AQuA#12]
Hi, I just tried 1p imaging analysis, but found that signal detecting was not so correct no matter what parameter that I tried.  So I wanna know that did you tried an 1p imaging data analysis?

**Comment by yu-lab-vt** [comment]
Yes, we have tested on 1p image data. To help you analyze your data, you can send a test example to yug@vt.edu. We also have an internal better version and are happy to share with you as long as we know who you are.
