### ISSUE TITLE
batch is not working as parameters_for_batch set

### ISSUE THREAD

**Issue by ZiTao956** [yu-lab-vt/AQuA#15]
I want to use aqua_cmd_batch.m to analyze multi files, so I test it by one tif file. I set the parameter in parameter_for_batch.csv, and all my settings for 'skip steps 2 and 3' are 1, which should mean the analyze will skip detecting super volxis, but I saw my Matlab is still running these steps. I also try to change the name from File1 to my filename,  but it doesn't make any changes. I have attached my parameters_for_batch.csv
[parameters_for_batch.csv](https://github.com/yu-lab-vt/AQuA/files/9990384/parameters_for_batch.csv)

**Comment by XuelongMi** [comment]
Thanks for reminding us, it's the problem in " aqua_cmd_batch.m" script. Now we've updated it to satisfy your requirements. If you have any questions, please let me know.

**Comment by ZiTao956** [comment]
Thank you for your quick update:) I try the new aqua_cmd_batch.m 
But when I run the script, just after it detects all the event, MATLAB close itself.

**Comment by XuelongMi** [comment]
It didn't occur on my computer using your parameter setting. Does that issue repeatly happen on your dataset? Could you check again, or test it on a smaller dataset? I suspect it may be memory issue.
