### ISSUE TITLE
Frame rate and spatial resolution of the processed image are getting overwritten by loading of existing settings

### ISSUE THREAD

**Issue by AlinaMarymonchyk** [yu-lab-vt/AQuA#17]
When loading Opts file of the previous analysis, the specific parameters to image are getting overwritten. So, for example, if you used different zoom or acquisition frequency for obtaining an image, you can no longer use the Opts file from previous experiment because it will overwrite spatialRes and frameRate parameters without you knowing that. The problem is that you don't see that these parameters change, because you type them in the "Load data" window and then you open the main window, and you think that Opts you load will be related only to the event detection parameters. This issue can lead to the incorrect analysis of propagation in case of even slight change of experimental design.  I think it should be either fixed or explicitly explained in the manual that you can't import the opts if you used a different frame rate or spatial resolution. Here is the possible fix https://github.com/yu-lab-vt/AQuA/pull/18

**Comment by XuelongMi** [comment]
Thanks for reminding us. We appreciate your suggestion and now the resolution won't be overwritten.
