### ISSUE TITLE
Super events and events all

### ISSUE THREAD

**Issue by DenovoW** [yu-lab-vt/AQuA#20]
Thanks for your contribution to the code!
Can you explain the difference between events all and super events generated in step3? Which parameters are considered while a super event or an event is defined?

**Comment by XuelongMi** [comment]
One super event may come from multiple sources, i.e., multiple events. In step 1, the tool estimates the noise level and baseline, then do a significant test to obtain active region. Then, based on the local maxima contained in active regions,

**Comment by XuelongMi** [comment]
One super event may come from multiple sources, i.e., multiple events. Let me introduce the framework from step 1 to step 3.

In step 1, the tool estimates the noise level and baseline, then do a significant test to obtain active regions. 

Step 2 is trying to grow local maxima contained in active regions spatially, neighbor pixels with similar peak properties will be added. Super voxels will be obtained.

Step 3 will first merge their super voxels according to the rising time. Super voxels with similar signal rising times will be merged, the obtained results are called a super event. It is worth noting that here didn't consider the propagation direction, super event is just a cluster of super voxels with similar rising times. It could come from multiple sources (cells). But in our definition, one event should rise a signal from a single source.
Like this example (consider the x-axis is the temporal dimension, y-axis is spatial dimension):
>>>
  >>>
       >>>
    >>>
>>>
In this example, the super event comes from two sources, thus needs to be segmented. And step 3 calculates the propagation pattern (propagation smoothness works here), identifies the source inside (rising time uncertainty works here), and does this segmentation (slowest delay in propagation works here) according to the propagation pattern.

Larger propagation smoothness, the obtained propagation pattern will be smoother.
Larger rising time uncertainty, the source identification will have more tolerance for the fluctuations in the propagation map.
Slowest delay in propagation is related to the continuity of event. A smaller value will let source segmentation assign pixels with close rising time to the same event, while a larger value depends more on spatial location to do segmentation.

**Comment by DenovoW** [comment]
Thank you! It seems more clear to me now. In step3 rising time is used to define the source of an event which may lead to different events generated in one cell that shared the same peak properties in step2.
