### ISSUE TITLE
About 3D AQuA

### ISSUE THREAD

**Issue by YiqunWang-FDU** [yu-lab-vt/AQuA#23]
Detecting events in 3D data using AQuA is mentioned in the Discussion section of the paper and in Supplementary Figure 12, and performs well. How can I repeat this process using aqua code, processing 3D data?
![image](https://github.com/yu-lab-vt/AQuA/assets/109506063/c59af1d1-72ac-42fc-b178-07d7cc6b65d0)

**Comment by XuelongMi** [comment]
Hi, there is the github for AQuA3D: github.com/yu-lab-vt/AQuA-3D. For this version, there is no GUI provided, you can only use "aqua_cmd.m" to process the data. And the format of input files are tiff files within one specific folder.

**Comment by 1209657459** [comment]
Sorry,I don't seem to have permission for this link."github.com/yu-lab-vt/AQuA-3D"
![image](https://github.com/yu-lab-vt/AQuA/assets/109506063/73650499-5c17-4dcf-85bc-03d31eedf8e6)

**Comment by XuelongMi** [comment]
Let me share it through google drive. https://drive.google.com/file/d/1dp3jUnvBW5XB9L46Sdgde-t_v-ZjiWxj/view?usp=sharing
