### ISSUE TITLE
The naming of some parameters in table is prone to misunderstanding

### ISSUE THREAD

**Issue by xujiameng** [yu-lab-vt/AQuA#24]
Spatial density is defined as the number of events that occur simultaneously with the current event (a subset in terms of time),  with code in line 81~87 of the function “getEvtNetworkFeatures”
`   
 % occur at same time
tLen0 = tLen(t0:t1);
tIdx0 = tIdx(t0:t1);
[x,ix] = max(tLen0);
tIdx0 = tIdx0{ix};
nOccurSameTime(ii) = x;
occurSameTimeList{ii} = tIdx0;
`
This seems to be more appropriately defined as "Temporal density." Alternatively, defining it as (the number of events in the same time period / (t1-t0)) seems feasible, but the "/ (t1-t0)" part is missing.
The parameters "Temporal density" and "Temporal density with similar size only" also appear to have the same issue in my view.

In addition, "Propagation onset one direction Antrior/Posterior/Left/Right"  is defined as the maximum increment in all adjacent frames, with code in line 148~155 of the function "getPropagationCentroidQuad"
`
prop = nan(size(sigDist));
prop(2:end,:,:) = sigDist(2:end,:,:) - sigDist(1:end-1,:,:);

propGrowMultiThr = prop; 
propGrowMultiThr(propGrowMultiThr<0) = nan; 
propGrow = nanmax(propGrowMultiThr,[],3); 
propGrow(isnan(propGrow)) = 0;
propGrowOverall = nansum(propGrow,1);
`

that is, the maximum speed at which the center of mass of the calcium event moves in a certain direction, rather than distance. 
The name of this parameter can be easily misunderstood as the distance of movement.

**Comment by XuelongMi** [comment]
Thank you for your reminder. We will modify these names.
