### ISSUE TITLE
custom LUT scale in Feature Overlay

### ISSUE THREAD

**Issue by MicaelaZ** [yu-lab-vt/AQuA#26]
When visualizing feature overlay (I am actually interested in Spatial and Temporal Density), the choice of feature value range is limited to min and max of the current movie. What if I want to obtain an image to be compared with another movie, in which min and max are different? Is there any way to impose a custom minimum and maximum (just for visualization purposes) independently from the "auto" range?
Thank you in advance
Micaela

**Comment by XuelongMi** [comment]
Hi Micaela, sorry for the late response. Are you mentioning the proofreading panel in the interface? 
The min and max values in the proofreading panel could be modified by users. By default, the min value and max value are the minimum and maximum of all detected events. It is not an "auto" range. After you modify the values, and click the check box, then only the events satisfying your limitations will be visualized. 
Or I misunderstand your question?

**Comment by XuelongMi** [comment]
Sorry, I cannot understand clearly. If you export the movie with event overlay of one time series, then the overlay is already fixed, and won't be impacted by other time series. There is no need to specify the min-max values. It just hides the events that do not satisfy the limitations. There is nothing related to red color.

Wait, are you saying in the right part you specify the feature that you want to check, then click the "update overlay" button, the events will be colored according to their features? It's not about the proofreading panel. There is no way to adjust the min-max value on the GUI, but you can modify it in the code. Let me tell you how to deal with it:
* Open AQuA\src\+ui\+over\reMapCol.m
* before line 1, manually set the min value and max value

----- you set -----
`
scl.minOv = XXX (you can set); 
`
`
scl.maxOv = XXX (you can set);
`
----- line 10 ----
`
v0(v0<scl.minOv) = scl.minOv;
`
`
v0(v0>scl.maxOv) = scl.maxOv;
`
Then the scroll bar of min and max value will have no use. The min value and max value for color coding will use the values you set.

**Comment by MicaelaZ** [comment]
Sorry, you are right, it is not the proofreading panel, I was wrong in my description!I thought that also that part was part of proofreading… You got perfectly the point, thank you so much, I will try your suggestion. Micaela  Micaela Zonta, Ph.D.Technologist at CNR Neuroscience Instituteand Biomedical Sciences DepartmentUniversity of Paduavia Ugo Bassi 58B35131 Padova - Italy Da: XuelongMiInviato: giovedì 28 settembre 2023 21:41A: yu-lab-vt/AQuACc: MicaelaZ; AuthorOggetto: Re: [yu-lab-vt/AQuA] custom LUT scale in Feature Overlay (Issue #26) Sorry, I cannot understand clearly. If you export the movie with event overlay of one time series, then the overlay is already fixed, and won't be impacted by other time series. There is no need to specify the min-max values. It just hides the events that do not satisfy the limitations. There is nothing related to red color.Wait, are you saying in the right part you specify the feature that you want to check, then click the "update overlay" button, the events will be colored according to their features? It's not about the proofreading panel. There is no way to adjust the min-max value on the GUI, but you can modify it in the code. Let me tell you how to deal with it:Open AQuA\src+ui+over\reMapCol.mbefore line 1, manually set the min value and max value----- you set -----scl.minOv = XXX (you can set); scl.maxOv = XXX (you can set);----- line 10 ----v0(v0<scl.minOv) = scl.minOv;v0(v0>scl.maxOv) = scl.maxOv;Then the scroll bar of min and max value will have no use. The min value and max value for color coding will use the values you set.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
