### ISSUE TITLE
What is the specific meaning of the third column in the parameter res.dffMatFilter?

### ISSUE THREAD

**Issue by xujiameng** [yu-lab-vt/AQuA#28]
In the main output, res.dffMatFilter is a matrix of size (num, Frame, 2), where the first column represents the calcium event index, and the second column contains the df/f values at different frames. However, I do not understand the specific meaning of the third column. Could you please explain? Thank you.

**Comment by XuelongMi** [comment]
dffMat(:,:,1) is the dff calculated from raw data. For example, dffMat(i,:,1) is the curve for event i.
dffMat(:,:,2) is the dff after removing the contributions from other events (like setting the values of other event voxels to nan value,  imputed by nearby values, then calculating dff).
