### ISSUE TITLE
Export/Save in Fiji returns SER files instead of a MATLAB file

### ISSUE THREAD

**Issue by AlexiaMt** [yu-lab-vt/AQuA#3]
Hi,

I have installed AQuA as a Fiji plugins on windows 10 and tried to run it on example data following the user guides in the Getting started section of the front page. I'm confused about a few things:

1. The 'save' and 'load' buttons don't appear next to 'cell boundaries' and 'landmarks':
![screenshot_1](https://user-images.githubusercontent.com/49063975/56454290-a5b1c280-634e-11e9-8c1f-9262fb2b8a77.png)

2. The 'Pan' and 'Zoom' buttons are merged into one 'PanAndZoom' button and left/right click on the movie doesn't do anything to zoom in or out.

3. When I select 'RisingMap' in the dropdown menu in the 'SidebySide' mode, the movie looks just like what I get by selecting 'Raw':
![screenshot_3](https://user-images.githubusercontent.com/49063975/56454526-8157e500-6352-11e9-9803-0c67446c84a9.png)

4. When I click 'Export/Save' I get a bunch of SER files that I can't figure how to read (I'd like to work on it in Python) instead of a MATLAB file as described in the pdf about details on output files, etc.
![screenshot_2](https://user-images.githubusercontent.com/49063975/56454291-a8141c80-634e-11e9-8256-e346203d6710.png)

Is all this expected on Fiji ? Do you know how I can get around it ?
Thanks in advance for helping.

**Comment by XuelongMi** [comment]
I'm Xuelong, I'm responsible for Fiji version, my email is mixl18@vt.edu, and if you have questions, you can contact me.

Thank you for your information!!!

If you are MATLAB user, I recommend you to use MATLAB version from https://github.com/yu-lab-vt/AQuA. Just download the code and run aqua_gui, then the tool will be the same as the descriptions in pdf.

Sorry about these problems, the Fiji version is finished before 2019. And there is a new update on Matlab version this January, the interface is changed according to users' suggestions. Fiji version is supposed to same as MATLAB version, but I'm working on other projects before, and my QE exam will proceed this May. I will update it before June.

And for your problems:
1. The interface and user guide is updated in MATLAB version this January, but Fiji version does not keep up with them. I will update it before June.
2. "PanAndZoom" button has the same functions of "Pan" and "Zoom" in Matlab version. You can use mouse wheel to enlarge and shrink the image, and drag the mouse to move the view.
3. Sorry about "RisingMap" term, that's function is not implemented in Fiji version. I'll finish it before June.
4. Fiji version is not supposed to output .mat file, the files are just used in processing. If it is neccessary and users want to see the intermediate results, it can be done.

**Comment by XuelongMi** [comment]
I've already updated Fiji version (The interface, the RisingMap ... ). But Fiji version cannot output ".mat" file like res. If you want to deal with the result in MATLAB, you can use the MATLAB version of Aqua.

**Comment by AlexiaMt** [comment]
I figured that my university has license for Matlab that I can use, so I'll do that.
Thank you for your work !
________________________________
De : XuelongMi [notifications@github.com]
Envoyé : lundi 27 mai 2019 22:56
À : yu-lab-vt/AQuA
Cc : Alexia Montalant; Author
Objet : Re: [yu-lab-vt/AQuA] Export/Save in Fiji returns SER files instead of a MATLAB file (#3)


I've already updated Fiji version (The interface, the RisingMap ... ). But Fiji version cannot output ".mat" file like res. If you want to deal with the result in MATLAB, you can use the MATLAB version of Aqua.
