### ISSUE TITLE
How is res.dffMatFilter calculated?

### ISSUE THREAD

**Issue by xujiameng** [yu-lab-vt/AQuA#30]
Hi XuelongMi, I would like to learn more about res.dffMatFilter. For example, how is the df/f curve of calcium events calculated? Is it the average fluorescence value on all regions of the calcium event in each frame? Or can you tell me the relevant functions and file location used for calculating the res.dffMatFilter parameter? This way, I can learn more details.

**Comment by XuelongMi** [comment]
It's in fea.getFeaturesTop.m
Like first calculating the average curve of the event, then using the minimum of this curve as baseline. Then calculate df/f
