### ISSUE TITLE
iglusnfr imaging data analysis: sigma issue

### ISSUE THREAD

**Issue by NeuroMDPhD** [yu-lab-vt/AQuA#31]
Thank you so much for creating such a wonderful analysis toolbox. I am working on iglusnfr imaging, and when creating a project, I use the preset GluSnFR_astrocytic_neuronal. However, I encounter the following error during the initial detection process:

-----------
An error occurred during use: imgaussfilt
Sigma must be positive.

Error occurred in: imgaussfilt>validateSigma (line 453)
validateattributes(sigma, {'numeric'}, {'real','nonsparse','positive','finite','nonempty'}, mfilename, 'Sigma');

Error occurred in: imgaussfilt>parseInputs (line 417)
    options.Sigma = validateSigma(varargin{2});

Error occurred in: imgaussfilt (line 121)
[A, options] = parseInputs(args{:});

Error occurred in: burst.getARSim (line 17)
dSim = imgaussfilt(dSim,[smo0 smo0]);

Error occurred in: burst.actTop (line 71)
        [arLst,dActVox] = burst.getARSim(datOrg,opts,evtSpatialMask,opts.smoXY,opts.thrARScl,opts.minSize);

Error occurred in: ui.detect.actRun (line 42)
[dat,dF,arLst,lmLoc,opts] = burst.actTop(datOrg,opts,evtSpatialMask,ff);

Error occurred in: ui.detect.flow (line 52)
            ui.detect.actRun([],[],f);
 
An error occurred while executing UIControl Callback.

Could you possibly ponder why this is happening? My guess is that the part where a smoothing value is input during the detection stage is something I can adjust, but I can't figure out the reason at all. I would love to be able to cite your paper in my research. Once again, I express my admiration for your fantastic development. Thank you.

**Comment by XuelongMi** [comment]
Hi, I've fixed this issue. You can download the updated version of AQuA for this problem, or just replace src\+burst\getARSim.m file with the updated one.
It seems that this function estimates the spatial correlation of noise, and then derives the smoothing factor "smo0" in the data. 
"smo0" is not the parameter you set, but something derived from the data, may imply the preprocessing before the analysis of AQuA.
"dSim = imgaussfilt(dSim,[smo0 smo0]);" tries to simulate the condition with such a smoothing factor, but it seems in your data it is 0, then "imgaussfilt" cannot work with 0 smoothing. 
Now I add one check before that "dSim = imgaussfilt(dSim,[smo0 smo0]);". If the factor is 0, then it will not run that line.

**Comment by NeuroMDPhD** [comment]
Wow, this is truly impressive. It appears I missed an update. Running the latest version solved the issue perfectly. Your prompt response has been of great assistance to me. I am profoundly grateful for your development, as it has significantly aided my research. I would like to extend my deepest thanks to you!
