### ISSUE TITLE
Could you further explain how do you calculate propagation distance (growing & shrinking)?

### ISSUE THREAD

**Issue by Jiaxinl7** [yu-lab-vt/AQuA#7]
Thanks for the useful tool! Regarding single event propagation, I have the following question:

1. How is distance calculated? 
Initially, from 1.3.3 example in your documentation, I thought it is the difference between centroids in frame _i_ and frame _i-1_, in each direction. But that cannot capture the change when the centroid is the same but the event grows. Then I saw in the result that all 4 directions could have a positive value, and realized my previous understanding might be wrong. So how is the distance calculated?

2. What is your growing & shrinking distance?
I understand your definition of growing and shrinking. But how come `propagation.propGrow ` and `propagation.propShrink ` seems different for the same event, same frame, same direction? Are they the change of centroid of growing and shrinking pixels respectively?

**Comment by freemanwyz** [comment]
1. For each event, at each frame, we calculate the growth/shrink in four orthogonal directions (by default, east, west, south, and north, but can be changed by specifying the anterior direction).  For example, to calculate the propagation distance in the north direction in frame `i`, we do the following:
    1. Find the centroid of the event at frame `i` and assume the centroid is `(xi, yi)`.
    2. Remove everything lower than `yi` in the image. Then find the new centroid of the event at frames `i` and `i+1`.
    3. Get the distance of centroid change

2. Assume for an event from frame `i` to `i+1`, let's consider the north direction only. Some part of the event becomes brighter than the threshold, some part becomes dimmer than the threshold between these two frames. According to our definition, it is both growing and shrinking in that direction. So `propGrow` and `propShrink` scores can be different for a same event, same time, and same direction. Although for an overall quantification of growing, you may subtract these two values.

**Comment by yu-lab-vt** [comment]
@Jiaxinl7 Are your problems addressed? If yes, I will close this issue.

**Comment by Jiaxinl7** [comment]
Thank you very much, my problems are addressed.
