### ISSUE TITLE
About 'res.dF' and 'res.dffMatFav' 

### ISSUE THREAD

**Issue by invincibleyue** [yu-lab-vt/AQuA#9]
dear Dr.Yu , Dr.Wang
      I am Yue Chen from Miao Jing Lab, Chinese institute for Brain Research, Beijing. Thank you very much for sharing the AQuA program which is very important for our experiment data analyzing. But we have some questions when we are using, We appreciate that if you could answer these questions ASAP.
1. Is **res.dF** A three-dimensional matrix of ΔF/F0 for the entire image sequence.
2. We found it have similar waveform but showed different ΔF/F0 curve in **res.dffMatFav(:,:,1)** (curve is higher) and averaged **res.dF** in **res.ftsFav.loc.x2D** (curve is lower) formed 3D cylinder formed.  So, how to derive from **res.dF** to **res.dffMatFav(:,:,1)**?

Looking forward your apply!
Thanks a lot
Yue 20210929

Dr. Yu ，Dr. Wang 您好，
       我是北京脑科学与类脑研究中心井淼实验室的陈阅，非常感谢您分享的AQuA程序，对我们的实验起到了非常重要的帮助。在使用过程中出现了一些问题希望得您到回复！
1.**res.dF**是否是对于整个图片序列的ΔF/F0的三维矩阵。
2.我们使用**res.dF** 在 **res.ftsFav.loc.x2D** 时间轴上扩展形成的三维柱体内的平均值作为ΔF/F0的值和**res.dffMatFav(:,:,1)**在波形上相似但是ΔF/F0数值上却有较大偏差，请问**res.dffMatFav(:,:,1)**是**res.dF**通过什么方式计算得出的呢？

期待您的回复
非常感谢
陈阅 20210929

% calculation method 
![image](https://user-images.githubusercontent.com/91582017/135208089-d1e0fdd5-8581-480c-95e1-9722996f6f48.png)
res.dF to ΔF/F0 matrix in ROIs

for i=1:length(res.ftsFav.loc.x2D)
ROI2D=zeros(502,502); %data size 502,502,2000
ROI2D(res.ftsFav.loc.x2D{1,i})=1;
ROI3D=double(res.dF).*ROI2D;
Mat(i,:)=sum(sum(ROI3D))./length(res.ftsFav.loc.x2D{1,i});
end

**Comment by invincibleyue** [comment]
Dear Dr. Wang
   Thank you very much for your timely reply!
    •  The mean is about 10000 to 50000 if I use one frame of ** res.datOrg** as F0 which has no signal. 
    •  Did you Normalize or use other calculations in ** res.datOrg** to processing F0？
•       Best Wishes ,
•       Yue 20210930

**Comment by freemanwyz** [comment]
If your movie does not have some global trend (like bleaching), I think using a frame with no signal as F0 is good.

We calculate F0 by fitting a polynomial curve for each event, which may remove the trend. Then we smooth the resulting curve and take the minimum value of the smoothed curve. If the events are very dense, we optionally remove these interfering events from the current event of interest. But if your data does not have these problems, your strategy is just fine.

**Comment by invincibleyue** [comment]
Thanks a lot 
if we want to show a ΔF/F0 image in some frame , What algorithm do you suggest we use to make the ΔF/F0 frame image same as **res.dffMatFav**? I want to use **res.dF** divide F0 (But averaged **res.datOrg** is about 30000 )
Yue

**Comment by freemanwyz** [comment]
I think your method is fine. Just choose a frame in raw data (res.datOrg) without signal. You don't need to use res.dF. Minus that frame from raw data, then divide by that frame.

To make the values numerically consistent, I suggest calculating per event ΔF/F0 the same way as above. For example, just extract the per event ΔF/F0 from the above-calculated maps. You can just ignore res.dffMatFav (due to the choice of per event F0 and the de-trending, they are not likely to be numerically the same as above).

**Comment by invincibleyue** [comment]
Thanks a lot !!
